# Generated by Django 5.1.4 on 2025-03-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustodiaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=50)),
                ('puntosMuestreoAutorizados', models.CharField(max_length=50)),
                ('modificacionOrdenTrabajo', models.BooleanField()),
                ('observacionesModificacion', models.TextField(blank=True, null=True)),
                ('muestreoRequerido', models.CharField(max_length=50)),
                ('fechaFinal', models.DateField()),
                ('horaFinal', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionCampo', models.CharField(max_length=50)),
                ('fechaMuestreo', models.DateField()),
                ('horaMuestreo', models.TimeField()),
                ('volumenCantidad', models.FloatField(blank=True, null=True)),
                ('numeroContenedor', models.CharField(max_length=50)),
                ('origenMuestra', models.CharField(max_length=50)),
                ('idLaboratorio', models.CharField(blank=True, max_length=50, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.contenedor')),
                ('custodiaExterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.custodiaexterna')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.filtro')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.matriz')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.parametro')),
            ],
        ),
        migrations.CreateModel(
            name='PreservadorMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.muestra')),
                ('preservador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.preservador')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='preservador',
            field=models.ManyToManyField(through='campo.PreservadorMuestra', to='campo.preservador'),
        ),
        migrations.CreateModel(
            name='RegistroCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregadoPor', models.CharField(max_length=100)),
                ('fechaEntrega', models.DateField()),
                ('horaEntrega', models.TimeField()),
                ('recibidoPor', models.CharField(max_length=100)),
                ('fechaEecepcion', models.DateField()),
                ('horaRecepcion', models.TimeField()),
                ('CustodiaExterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campo.custodiaexterna')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='tipoMuestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campo.tipomuestra'),
        ),
    ]
