# Generated by Django 5.1.4 on 2025-03-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_alter_filtro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campo.filtro'),
        ),
    ]
