# Generated by Django 5.1.4 on 2025-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_alter_muestra_filtro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiaexterna',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custodiaexterna',
            name='horaFinal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custodiaexterna',
            name='observaciones',
            field=models.TextField(blank=True, max_length=325, null=True),
        ),
        migrations.AlterField(
            model_name='custodiaexterna',
            name='observacionesModificacion',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
