# Generated by Django 5.1.4 on 2025-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0004_alter_custodiaexterna_fechafinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiaexterna',
            name='puestoCargoContacto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
