# Generated by Django 5.1.4 on 2025-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0005_custodiaexterna_puestocargocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodiaexterna',
            name='puestoCargoContacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
