# Generated by Django 5.1.4 on 2025-03-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0006_alter_custodiaexterna_puestocargocontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiaexterna',
            name='asesoriaGestionAmbiental',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
