# Generated by Django 5.1.4 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0007_custodiaexterna_asesoriagestionambiental'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiaexterna',
            name='celularContacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
