# Generated by Django 5.1.4 on 2025-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0008_custodiaexterna_celularcontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiaexterna',
            name='correoContacto',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
