# Generated by Django 5.1.4 on 2025-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0009_custodiaexterna_correocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
