# Generated by Django 5.1.4 on 2025-04-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0010_estadocustodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodiaexterna',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campo.estadocustodia'),
            preserve_default=False,
        ),
    ]
