# Generated by Django 5.1.4 on 2025-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0011_custodiaexterna_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestra',
            name='tipoMuestra',
        ),
        migrations.AddField(
            model_name='custodiaexterna',
            name='idMuestraCompuesta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custodiaexterna',
            name='idMuestraPuntual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custodiaexterna',
            name='muestraCompuesta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custodiaexterna',
            name='muestraPuntual',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoMuestra',
        ),
    ]
